### ISSUE TITLE
virtualizor.py: Hardcoded value of emulator path

### ISSUE THREAD

**Issue by dsavineau** [enovance/infra-virt#19]
If the hypervisor node is running RHEL7 the vm definition will failed because the path of emulator is different :

/usr/libexec/qemu-kvm

https://github.com/enovance/infra-virt/blob/master/virtualizor.py#L192

**Comment by goneri** [comment]
I agree, we should have a variable here. That's the location of the binary from qemu-2. You can get it from EPEL.
